[workspace]

members = [
  "semantics/oca-bundle",
  "semantics/oca-file",
  "semantics/oca-ast",
  "semantics/oca-dag",
  "oca",
  "oca-file",
  "transformation/ast",
  "transformation/ocafile",
  "transformation/transformation-file",

  "tests",
]

resolver = "2"
