publish=false
pre-release-replacements = [
  {file="bindings/js/wasm/Cargo.toml", search="\nversion = \"[a-z0-9\\.-]+\"", replace="\nversion = \"{{version}}\"", exactly=1, prerelease=true},
  {file="README.md", search="oca-bundle = .*", replace="oca-bundle = \"{{version}}\""},
]
# pre-release-hook = ["bash", "release-wasm-hook.sh"]
