publish = false
# pre-release-hook = ["bash", "release-wasm-hook.sh"]

[[pre-release-replacements]]
file = "README.md"
search = "oca-bundle = .*"
replace = "oca-bundle = \"{{version}}\""

[[pre-release-replacements]]
file = "Cargo.toml"
search = "oca-ast-semantics = . version = \"[a-z0-9\\.-]+\""
replace = "oca-ast-semantics = { version = \"{{version}}\""
exactly = 1
prerelease = true
