[package]
name = "oca-rs"
version = "0.3.0-rc.21"
edition = "2021"
authors = ["Marcin Olichwiruk <marcin.olichwiruk@opensoftware.pl>", "Robert Mitwicki <robert.mitwicki@opensoftware.pl>", "Michał Pietrus <michal.pietrus@opensoftware.pl>"]
license = "EUPL-1.2"
readme = "README.md"
description = "OCA rust ecosytem facade"

[lib]
name = "oca_rs"
path = "src/lib.rs"

[dependencies]
convert_case = "0.6.0"
dyn-clonable = "0.9.0"
isolang = "2.3.0"
oca-ast = { version = "0.3.0-rc.21", path = "../oca-ast" }
oca-bundle = { version = "0.3.0-rc.21", path = "../oca-bundle", features = [
  "format_overlay",
] }
oca-dag = { version = "0.3.0-rc.21", path = "../oca-dag" }
oca-file = { version = "0.3.0-rc.21", path = "../oca-file" }
regex = "1.9.5"
rusqlite = "0.29.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sled = "0.34.7"
thiserror = "1.0.49"
