[package]
name = "oca-rs"
version = "0.3.0-rc.8"
edition = "2021"
authors = ["Marcin Olichwiruk <marcin.olichwiruk@opensoftware.pl>", "Robert Mitwicki <robert.mitwicki@opensoftware.pl>", "Michał Pietrus <michal.pietrus@opensoftware.pl>"]
license = "EUPL-1.2"
readme = "README.md"
description = "OCA rust ecosytem facade"

[lib]
name = "oca_rs"
path = "src/lib.rs"

[dependencies]
convert_case = "0.6.0"
dyn-clonable = "0.9.0"
oca-ast = "0.3.0-rc.6"
oca-bundle = { version = "0.3.0-rc.7", features = ["format_overlay"] }
oca-file = "0.3.0-rc.6"
oca-dag = "0.3.0-rc.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sled = "0.34.7"
