publish = false

[[pre-release-replacements]]
file = "Cargo.toml"
search = "oca-ast-semantics = . version = \"[a-z0-9\\.-]+\""
replace = "oca-ast-semantics = { version = \"{{version}}\""
exactly = 1
prerelease = true

[[pre-release-replacements]]
file = "Cargo.toml"
search = "oca-bundle-semantics = . version = \"[a-z0-9\\.-]+\""
replace = "oca-bundle-semantics = { version = \"{{version}}\""
exactly = 1
prerelease = true

[[pre-release-replacements]]
file = "Cargo.toml"
search = "oca-dag-semantics = . version = \"[a-z0-9\\.-]+\""
replace = "oca-dag-semantics = { version = \"{{version}}\""
exactly = 1
prerelease = true

[[pre-release-replacements]]
file = "Cargo.toml"
search = "oca-file-semantics = . version = \"[a-z0-9\\.-]+\""
replace = "oca-file-semantics = { version = \"{{version}}\""
exactly = 1
prerelease = true

[[pre-release-replacements]]
file = "Cargo.toml"
search = "transformation-file = . version = \"[a-z0-9\\.-]+\""
replace = "transformation-file = { version = \"{{version}}\""
exactly = 1
prerelease = true
