publish = false

[[pre-release-replacements]]
file = "Cargo.toml"
search = "oca-ast-transformation = . version = \"[a-z0-9\\.-]+\""
replace = "oca-ast-transformation = { version = \"{{version}}\""
exactly = 1
prerelease = true
