name: Add bins to assets

on:
  push:
    tags:
      - "v*"
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
      - name: Add x86_64-pc-windows-gnu target
        run: rustup target add x86_64-pc-windows-gnu
      - name: Run tests
        run: cargo test --all-features --verbose
      - name: Install mingw-w64
        run: sudo apt-get install -y mingw-w64
      - name: Build x86_64-pc-windows-gnu
        run:  cargo build --features command_line,xls_parser --target x86_64-pc-windows-gnu --release --verbose
      - name: Build x86_64-unknown-linux-gnu
        run: cargo build --features command_line,xls_parser --target x86_64-unknown-linux-gnu --release --verbose
      - uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          gzip: folders
          files: >
            parser.bin:target/x86_64-unknown-linux-gnu/release/parser
            parser.exe:target/x86_64-pc-windows-gnu/release/parser.exe
