name: Publish oca-dag to crates.io

on:
  push:
    tags:
      - "oca-dag-v*"
env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: oca-dag

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
      - name: Check
        run: cargo check
      - name: Run tests
        run: cargo test --verbose
      - uses: katyo/publish-crates@v1
        with:
            path: './oca-dag'
            registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
